name: pic_env
dependencies:
  - python=3.8
  - pip
  - pip:
      - torch>=1.5.1
      - gym>=0.17.2
      - dm2gym
      - numpy
      - pillow
      - optuna
      - cloudpickle==1.3.0
      - cycler==0.10.0
      - future==0.18.2
      - kiwisolver==1.2.0
      - matplotlib
      - pandas
      - pyglet==1.5.0
      - pyparsing==2.4.7
      - python-dateutil==2.8.1
      - pytz==2020.1
      - scipy
      - seaborn
      - six
      - tabulate==0.8.7

